// letsignoreManager.idl


#include "nsISupports.idl"
#include "MozIStorageStatementCallback.idl"

[scriptable, uuid(94962e56-11fc-4b28-b574-b87a4c690e5b)]
interface rbILetsignoreManager : nsISupports
{
    
  readonly attribute boolean initialized;

  void initialize();

  AString getConfig();

  void ignore(in AString topic,
              in AString datastr);
  
  void unignore(in AString topic,
                in AString datastr);

  void getIgnored(in AString topic,
                  in MozIStorageStatementCallback callback);

  boolean isIgnored(in AString topic,
                    in AString value);

};

